### ISSUE TITLE
Chinese simplifed translate not working via DeepL

### ISSUE THREAD

**Issue by PrimozRome** [voorhoede/datocms-plugin-translate-fields#5]
This in an excellent plugin, very useful. I am using DeepL translator with FREE plan.

The one issue I am having is it does not translate the Chinese (Simplified) locale (zh-CN). The plugin returns "DEEPL returned status 400". It still translates all other locales, except Chinese...

<img width="1552" alt="Screenshot 2022-07-23 at 14 20 17" src="https://user-images.githubusercontent.com/1180467/180604620-e42b0350-448a-4096-a510-29d4d5edc359.png">

<img width="1552" alt="Screenshot 2022-07-23 at 14 20 23" src="https://user-images.githubusercontent.com/1180467/180604624-0a623c47-b127-4a6d-b234-4f336e14b82b.png">

**Comment by velomovies** [comment]
Hi @PrimozRome, thanks for using this plugin!

This looks like a problem within DeepL where the locale `zh-CN` isn't supported. 
[Here](https://www.deepl.com/docs-api/translating-text/request/) you can see a list of locales that are supported with DeepL.

The easiest solution would be to use the `zh` locale as translation (selecting `Chinese` instead of `Chinese (Simplified, China)`), which will solve the 400 error.

**Comment by PrimozRome** [comment]
Hi,

okay understand. But that means I would have to remove `zh-CN` and all all texts again in `zh` locale, which means a lot of work. Could a plugin be upgraded in a way that treats both locales as `zh`?

DeepL has Chines (Simplified) translation, but looks like locale behind is not `zh-CN`

<img width="2031" alt="Screenshot 2022-07-25 at 10 41 11" src="https://user-images.githubusercontent.com/1180467/180735642-3fff1d78-001a-4c0d-adf6-027ddae48958.png">

Kind regards,
Primoz

**Comment by velomovies** [comment]
We have updated the plugin. It will now map all locales to use the correct supported locale (so for example `zn-CH` will use the supported language `zn`. 

If the locale isn't supported at all (like `af` or `mt` for DeepL) it will still give a 400 status error. To make them work you should consider a different translate tool (like yandex). 

You can use `v1.2.0` when Dato has picked up the updated plugin

**Comment by PrimozRome** [comment]
@velomovies that is awesome, thank you. 

One question. Do I need to remove and install the plugin again to get the new version, or DatoCMS updates that automatically?

**Comment by velomovies** [comment]
You should be able to update the pluign from the plugins page in your Dato project. There should be a button where you can update the plugin. Something like:

<img width="911" alt="Update plugin" src="https://user-images.githubusercontent.com/22169955/180790768-8a0406ed-4d7a-47b8-8c30-ef6c56a6a111.png">

**Comment by PrimozRome** [comment]
Perfect, I will check!

**Comment by PrimozRome** [comment]
Hi @velomovies 

Looks like the Chinese translations still have problem... See the screen recording.

https://user-images.githubusercontent.com/1180467/183075160-61a2e079-cfe9-486e-b922-6b9d20273b5f.mov
